### ISSUE TITLE
Releases of these mods should NOT be version-specific

### ISSUE THREAD

**Issue by HebaruSan** [linuxgurugamer/KSPAddonVersionChecker#33]
![image](https://user-images.githubusercontent.com/1559108/72209735-2386a280-3477-11ea-8ea1-7d6d67fc63c1.png)

This doesn't make sense. The point of KSP-AVC is to alert the user when a mod is installed on the wrong version of KSP. This means KSP-AVC itself *inherently needs to support running on any version of KSP*, so it can perform the appropriate checks and raise warnings. Making KSP-AVC and/or MiniAVC version-specific defeats the purpose of both mods.

**Comment by linuxgurugamer** [comment]
There are working versions of the mod for all of the previous versions of KSP.
MiniAVC especially is broken in 1.8.1 due to the engine change.  Similarly, the 1.7.3 version of KSP-AVC is broken when running on 1.8.x due to the engine change.
The previous author was using real threads, Unity is not thread safe, and the threaded versions of KSP-AVC and MiniAVC were causing crashes to desktop.

**Comment by HebaruSan** [comment]
![image](https://user-images.githubusercontent.com/1559108/134819142-b503fa86-2aea-4843-92d6-9a980c9f5b8f.png)
